kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: admin-server
  labels:
    serviceType: SERVER
    weblogic.domainName: app1-domain
    weblogic.domainUID: app1-domain
spec:
  path: /console
  to:
    kind: Service
    name: app1-domain-admin-server
    weight: 100
  port:
    targetPort: internal-t3
  wildcardPolicy: None

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: app1-cluster
  labels:
    serviceType: CLUSTER
    weblogic.clusterName: app1-cluster
    weblogic.domainName: app1-domain
    weblogic.domainUID: app1-domain
spec:
  path: /
  to:
    kind: Service
    name: app1-domain-cluster-app1-cluster
    weight: 100
  port:
    targetPort: default
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
