apiVersion: v1
kind: Secret
metadata:
  name: weblogic-credentials
stringData:
  username: weblogic
  password: P4ssw0rd!

---
apiVersion: v1
kind: Secret
metadata:
  name: domain-runtime-encryption-secret
stringData:
  password: P4ssw0rd!