# Admin server
AdminServer.name=admin-server
AdminServer.listenPort=7001
AdminServer.SSL.listenPort=7002

# Server template, used by Managed Server
ServerTemplate.server-template-1.listenPort=8001
ServerTemplate.server-template-1.SSL.listenPort=8100

# Managed server
ManagedServer.serverNamePrefix=managed-server
ManagedServer.serverTemplateName=server-template-1
ManagedServer.maxDynamicServerCount=1
